//
//  PacFileService.swift
//  MagentX
//
//  Author: MarlinL
//  Responsibility: Generates and persists PAC files from proxy rule snapshots.
//

import Foundation
import Magent

/// PAC 文件服务，负责把代理规则快照编译为本地代理使用的 host PAC 文件。
final class PacFileService {
    static let shared = PacFileService()
    nonisolated static let fileName = "proxy.pac"

    let directoryURL: URL

    /// 创建 PAC 文件服务，默认写入用户 Home 下的 `.MagentX` 目录。
    init(directoryURL: URL = PacFileService.defaultDirectoryURL()) {
        self.directoryURL = directoryURL
    }

    /// 当前服务负责维护的 PAC 文件路径。
    var proxyHostPACURL: URL {
        Self.proxyHostPACURL(in: directoryURL)
    }

    /// 用轻量规则快照原子覆盖 proxy host PAC 文件。
    @discardableResult
    nonisolated static func writeProxyHostPAC(
        rules: [Rule],
        proxyEndpoint: ProxyEndpoint,
        directoryURL: URL
    ) throws -> URL {
        let fileManager = FileManager.default
        try fileManager.createDirectory(at: directoryURL, withIntermediateDirectories: true)

        let fileURL = proxyHostPACURL(in: directoryURL)
        let pacBody = makeProxyHostPAC(rules: rules, proxyEndpoint: proxyEndpoint)
        try pacBody.write(to: fileURL, atomically: true, encoding: .utf8)
        return fileURL
    }

    /// 生成完整 proxy host PAC 文件内容；没有规则命中时默认直连。
    nonisolated static func makeProxyHostPAC(
        rules: [Rule],
        proxyEndpoint: ProxyEndpoint
    ) -> String {
        let sortedRules = rules.sorted { leftRule, rightRule in
            if leftRule.order != rightRule.order {
                return leftRule.order < rightRule.order
            }
            if leftRule.matchType.rawValue != rightRule.matchType.rawValue {
                return leftRule.matchType.rawValue < rightRule.matchType.rawValue
            }
            return leftRule.matchValue.localizedStandardCompare(rightRule.matchValue) == .orderedAscending
        }
        let ruleLines = sortedRules
            .compactMap { rule in
                ruleLiteral(rule)
            }
            .map { "        \($0)" }
            .joined(separator: ",\n")
        let proxyValue = "SOCKS5 \(proxyEndpoint.address):\(proxyEndpoint.port); DIRECT"

        return """
        // Generated by MagentX. Do not edit by hand.
        function FindProxyForURL(url, host) {
            var proxy = \(javaScriptStringLiteral(proxyValue));
            var normalizedHost = (host || "").toLowerCase();
            var hostIP = null;
            var rules = [
        \(ruleLines)
            ];

            function domainSuffixMatch(value) {
                if (normalizedHost === value) { return true; }
                if (normalizedHost.length <= value.length) { return false; }
                return normalizedHost.substring(normalizedHost.length - value.length - 1) === "." + value;
            }

            function resolvedHostIP() {
                if (hostIP !== null) { return hostIP; }
                hostIP = dnsResolve(normalizedHost) || normalizedHost;
                return hostIP;
            }

            function regexMatch(pattern) {
                try {
                    return new RegExp(pattern).test(url);
                } catch (_) {
                    return false;
                }
            }

            function ruleMatches(rule) {
                if (rule.type === "exactDomain") { return normalizedHost === rule.value; }
                if (rule.type === "domainSuffix") { return domainSuffixMatch(rule.value); }
                if (rule.type === "domainKeyword") { return normalizedHost.indexOf(rule.value) !== -1; }
                if (rule.type === "ipCIDR") { return isInNet(resolvedHostIP(), rule.value, rule.mask); }
                if (rule.type === "urlRegex") { return regexMatch(rule.value); }
                return false;
            }

            for (var index = 0; index < rules.length; index += 1) {
                var rule = rules[index];
                if (ruleMatches(rule)) {
                    return rule.decision === "direct" ? "DIRECT" : proxy;
                }
            }

            return "DIRECT";
        }
        """
    }

    /// 返回指定目录下的 proxy host PAC 文件路径。
    nonisolated static func proxyHostPACURL(in directoryURL: URL) -> URL {
        directoryURL.appendingPathComponent(fileName, isDirectory: false)
    }

    /// 返回默认的 `~/.MagentX` 目录路径。
    nonisolated static func defaultDirectoryURL() -> URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".MagentX", isDirectory: true)
    }

    nonisolated private static func ruleLiteral(_ rule: Rule) -> String? {
        let type = javaScriptStringLiteral(rule.matchType.rawValue)
        let normalizedValue = rule.matchType == .urlRegex ? rule.matchValue : rule.matchValue.lowercased()
        let value = javaScriptStringLiteral(normalizedValue)
        let decision = javaScriptStringLiteral(rule.decision)

        switch rule.matchType {
        case .exactDomain, .domainSuffix, .domainKeyword, .urlRegex:
            return "{ type: \(type), value: \(value), decision: \(decision) }"
        case .ipCIDR:
            guard let cidr = CIDR(value: rule.matchValue) else { return nil }
            return "{ type: \(type), value: \(javaScriptStringLiteral(cidr.network)), mask: \(javaScriptStringLiteral(cidr.mask)), decision: \(decision) }"
        }
    }

    nonisolated private static func javaScriptStringLiteral(_ value: String) -> String {
        var literal = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
            case 0x08:
                literal += "\\b"
            case 0x09:
                literal += "\\t"
            case 0x0A:
                literal += "\\n"
            case 0x0C:
                literal += "\\f"
            case 0x0D:
                literal += "\\r"
            case 0x22:
                literal += "\\\""
            case 0x5C:
                literal += "\\\\"
            case 0x00...0x1F:
                literal += String(format: "\\u%04X", scalar.value)
            default:
                literal.unicodeScalars.append(scalar)
            }
        }
        literal += "\""
        return literal
    }
}

/// PAC 文件中的轻量规则快照。
extension PacFileService {
    nonisolated struct Rule: Equatable, Sendable {
        let matchType: MatchType
        let matchValue: String
        let decision: String
        let order: Int

        /// 创建可跨线程传递的 PAC 规则快照。
        nonisolated init(
            matchType: MatchType,
            matchValue: String,
            decision: String,
            order: Int
        ) {
            self.matchType = matchType
            self.matchValue = matchValue
            self.decision = decision
            self.order = order
        }
    }
}

/// PAC 文件使用的本地代理端点。
extension PacFileService {
    nonisolated struct ProxyEndpoint: Equatable, Sendable {
        let address: String
        let port: Int

        /// 从常规设置中的代理监听字段创建 PAC 使用的代理端点。
        init(generalSettings: GeneralSettings) throws {
            try self.init(
                address: generalSettings.proxyListenAddress,
                port: generalSettings.proxyListenPort
            )
        }

        /// 创建已校验的本地代理端点。
        init(address: String, port: Int) throws {
            let normalizedAddress = address.trimmingCharacters(in: .whitespacesAndNewlines)
            guard normalizedAddress.isEmpty == false else {
                throw MagentXError.invalidListenAddress(address)
            }
            guard (1...65535).contains(port) else {
                throw MagentXError.invalidListenPort(port)
            }
            self.address = normalizedAddress
            self.port = port
        }
    }
}

/// IPv4 CIDR PAC 匹配所需的网络地址和子网掩码。
nonisolated private struct CIDR {
    let network: String
    let mask: String

    init?(value: String) {
        let parts = value.split(separator: "/")
        guard parts.count == 2,
              Self.isIPv4Address(String(parts[0])),
              let prefixLength = Int(parts[1]),
              (0...32).contains(prefixLength)
        else {
            return nil
        }

        self.network = String(parts[0])
        self.mask = Self.mask(prefixLength: prefixLength)
    }

    private static func isIPv4Address(_ value: String) -> Bool {
        let parts = value.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 4 else { return false }
        return parts.allSatisfy { UInt8($0) != nil }
    }

    private static func mask(prefixLength: Int) -> String {
        let mask = prefixLength == 0 ? UInt32(0) : UInt32.max << (32 - prefixLength)
        return [
            (mask >> 24) & 0xFF,
            (mask >> 16) & 0xFF,
            (mask >> 8) & 0xFF,
            mask & 0xFF
        ]
        .map(String.init)
        .joined(separator: ".")
    }
}
