//
//  PACUtil.swift
//  MagentX
//
//  Author: MarlinL
//  Responsibility: Generates PAC file content from proxy rules.
//

import Foundation
import Magent

/// PAC 内容生成工具，负责把代理规则转换为 JavaScript 文本。
enum PACUtil {
    /// 按规则优先级生成完整的 PAC JavaScript；不读取数据库，也不写入文件。
    /// - Parameters:
    ///   - rules: 需要写入 PAC 的持久化代理规则。
    /// - Returns: 完整的 PAC JavaScript 文本。
    nonisolated static func makePACBody(rules: [MagentProxyRule]) -> String {
        let sortedRules = rules.sorted { leftRule, rightRule in
            if leftRule.order != rightRule.order {
                return leftRule.order < rightRule.order
            }
            if leftRule.matchType.rawValue != rightRule.matchType.rawValue {
                return leftRule.matchType.rawValue < rightRule.matchType.rawValue
            }
            return leftRule.matchValue.localizedStandardCompare(rightRule.matchValue) == .orderedAscending
        }
        let ruleLines = sortedRules
            .compactMap(ruleLiteral)
            .map { "        \($0)" }
            .joined(separator: ",\n")
        let proxyValue = "SOCKS5 127.0.0.1:1086; DIRECT"

        return """
        // Generated by MagentX. Do not edit by hand.
        function FindProxyForURL(url, host) {
            var proxy = \(javaScriptStringLiteral(proxyValue));
            var normalizedHost = (host || "").toLowerCase();
            var hostIP = null;
            var rules = [
        \(ruleLines)
            ];

            function domainSuffixMatch(value) {
                if (normalizedHost === value) { return true; }
                if (normalizedHost.length <= value.length) { return false; }
                return normalizedHost.substring(normalizedHost.length - value.length - 1) === "." + value;
            }

            function resolvedHostIP() {
                if (hostIP !== null) { return hostIP; }
                hostIP = dnsResolve(normalizedHost) || normalizedHost;
                return hostIP;
            }

            function regexMatch(pattern) {
                try {
                    return new RegExp(pattern).test(url);
                } catch (_) {
                    return false;
                }
            }

            function ruleMatches(rule) {
                if (rule.type === "exactDomain") { return normalizedHost === rule.value; }
                if (rule.type === "domainSuffix") { return domainSuffixMatch(rule.value); }
                if (rule.type === "domainKeyword") { return normalizedHost.indexOf(rule.value) !== -1; }
                if (rule.type === "ipCIDR") { return isInNet(resolvedHostIP(), rule.value, rule.mask); }
                if (rule.type === "urlRegex") { return regexMatch(rule.value); }
                return false;
            }

            for (var index = 0; index < rules.length; index += 1) {
                var rule = rules[index];
                if (ruleMatches(rule)) {
                    return rule.decision === "direct" ? "DIRECT" : proxy;
                }
            }

            return "DIRECT";
        }
        """
    }

    /// 将单条代理规则转换为 PAC JavaScript 对象字面量；无效 CIDR 返回 `nil`。
    nonisolated private static func ruleLiteral(_ rule: MagentProxyRule) -> String? {
        let type = javaScriptStringLiteral(rule.matchType.rawValue)
        let normalizedValue = rule.matchType == .urlRegex ? rule.matchValue : rule.matchValue.lowercased()
        let value = javaScriptStringLiteral(normalizedValue)
        let decision = javaScriptStringLiteral(rule.decision.rawValue)

        switch rule.matchType {
        case .exactDomain, .domainSuffix, .domainKeyword, .urlRegex:
            return "{ type: \(type), value: \(value), decision: \(decision) }"
        case .ipCIDR:
            guard let cidr = PACCIDR(value: rule.matchValue) else { return nil }
            return "{ type: \(type), value: \(javaScriptStringLiteral(cidr.network)), mask: \(javaScriptStringLiteral(cidr.mask)), decision: \(decision) }"
        }
    }

    nonisolated private static func javaScriptStringLiteral(_ value: String) -> String {
        var literal = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
            case 0x08:
                literal += "\\b"
            case 0x09:
                literal += "\\t"
            case 0x0A:
                literal += "\\n"
            case 0x0C:
                literal += "\\f"
            case 0x0D:
                literal += "\\r"
            case 0x22:
                literal += "\\\""
            case 0x5C:
                literal += "\\\\"
            case 0x00...0x1F:
                literal += String(format: "\\u%04X", scalar.value)
            default:
                literal.unicodeScalars.append(scalar)
            }
        }
        literal += "\""
        return literal
    }
}

/// IPv4 CIDR PAC 匹配所需的网络地址和子网掩码。
private struct PACCIDR {
    let network: String
    let mask: String

    /// 解析 IPv4 CIDR，并生成 PAC `isInNet` 所需的网络地址和子网掩码。
    nonisolated init?(value: String) {
        let parts = value.split(separator: "/")
        guard parts.count == 2,
              Self.isIPv4Address(String(parts[0])),
              let prefixLength = Int(parts[1]),
              (0...32).contains(prefixLength)
        else {
            return nil
        }

        network = String(parts[0])
        mask = Self.mask(prefixLength: prefixLength)
    }

    /// 判断字符串是否为四段合法的 IPv4 地址。
    nonisolated private static func isIPv4Address(_ value: String) -> Bool {
        let parts = value.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 4 else { return false }
        return parts.allSatisfy { UInt8($0) != nil }
    }

    /// 将 CIDR 前缀长度转换为 PAC `isInNet` 使用的点分十进制掩码。
    nonisolated private static func mask(prefixLength: Int) -> String {
        let mask = prefixLength == 0 ? UInt32(0) : UInt32.max << (32 - prefixLength)
        return [
            (mask >> 24) & 0xFF,
            (mask >> 16) & 0xFF,
            (mask >> 8) & 0xFF,
            mask & 0xFF
        ]
        .map(String.init)
        .joined(separator: ".")
    }
}
